services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: "host"
    volumes:
      - /home/giacomo/adguardhome/work:/opt/adguardhome/work
      - /home/giacomo/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
